# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Prompt Engineering Logo
subtitle: Public domain logotype for anyone can legally use it without permission
name: Maxim Salnikov
email: salnikov@gmail.com
repository: webmaxru/prompt-engineering-logo
url: https://logo.promptengineering.rocks
baseurl: /
logo: /assets/prompt-engineering-logo%20(black).png
og_image: /promo/social.png
description: >- # this means to ignore newlines until "baseurl:"
  Logo for the Prompt Engineering as a new emerging discipline. It's in the public domain, so anyone can legally use it without permission.
twitter_username: webmaxru
github_username: webmaxru
minimal_mistakes_skin: dirt
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-include-cache

author:
  name   : "Maxim Salnikov"
  avatar : "https://avatars.githubusercontent.com/u/1560278?v=4"
  bio    : "Maxim Salnikov is a tech and cloud community enthusiast based in Oslo. He is an experienced web developer who has been creating applications since the end of the last century and shares his extensive knowledge of web platform, cloud computing, and AI by speaking and providing training at developer events around the world. During the day, Maxim helps to improve cloud and AI skills in European companies by leading the developer productivity business at Microsoft. In the evenings, he can be found organizing Norway's largest web and cloud development meetups."
  links:

    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/webmaxru/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/webmaxru/"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://logo.promptengineering.rocks/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/webmaxru/prompt-engineering-logo/"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
